# Generated by Django 3.1.6 on 2021-02-10 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('VCS', 'Version Control Systems (Git)'), ('CLI', 'Command Line Interface'), ('I/O', 'Input/Output'), ('OBJ', 'Object Types — Arrays, Hashes, Strings, Integers, Floats, Symbols, Ranges, Booleans etc.'), ('REX', 'Regular Expressions'), ('OPR', '&&/||/! Operators'), ('WWF', 'Working with files'), ('FLC', 'Flow Control'), ('LOO', 'Looping'), ('ABS', 'Abstraction'), ('BUG', 'Debugging'), ('M/F', 'Methods/Functions'), ('MUT', 'Mutation'), ('SEL', 'Selection'), ('TRA', 'Transformation'), ('ITE', 'Iteration'), ('REV', 'Return Values'), ('PST', 'General Problem Solving & Computational Thinking'), ('PPR', 'Procedural Programming'), ('VAA', 'Variable Assignment'), ('VAS', 'Variable Scope'), ('VAT', 'Variable Types — Constant, Local, Instance, Class.'), ('OEV', 'Object Evaluation Strategy (pass by value, pass by reference value, pass by reference)'), ('OOP', 'OOP — Polymorphism, Composition, Encapsulation, Inheritance'), ('C/H', 'Callbacks/Hooks'), ('OBJ', 'Objects'), ('CIM', 'Class/Instance Methods'), ('ISS', 'OOP keywords — include, self, super'), ('MOD', 'Modules'), ('ERR', 'Error Handling'), ('ENU', 'Enumerators'), ('BLO', 'Blocks'), ('CLO', 'Closures'), ('BIN', 'Binding'), ('ASS', 'Assertions'), ('TES', 'Testing')], max_length=3)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
