# Generated by Django 3.1.6 on 2021-02-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_languages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='description',
        ),
        migrations.AddField(
            model_name='languages',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
    ]
